stages:
- name: compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: base-64:latest
      registry: 127.0.0.1:34992
timeout: 60
notification: {}
