stages:
- name: compile
  steps:
  - runScriptConfig:
      image: ubuntu:xenial
      shellScript: |-
        bash configure.sh
        sudo su - cub
        ./install.sh
timeout: 60
notification: {}
