stages:
- name: Build Temporary System
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: temp-system:latest
      pushRemote: true
      registry: 127.0.0.1:34992
timeout: 60
notification: {}
