stages:
- name: Build Temporary System
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile.temp
      buildContext: .
      tag: pandalinux/temp-system:latest
      pushRemote: true
      registry: index.docker.io
timeout: 60
notification: {}
