#!/usr/bin/env bash

# # # # # # # # # # # # # # # # # # # # # # # # # #
# GLOBAL VARIABLES TO BE USED BY THE INSTALLER
#
# DO NOT EDIT THIS FILE
# # # # # # # # # # # # # # # # # # # # # # # # # #

# Path of current script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Set fonts for Help.
NORM=`tput sgr0`
BOLD=`tput bold`
REV=`tput smso`
RED=`tput setaf 1`
GREEN=`tput setaf 2`
YELLOW=`tput setaf 3`
