#!/usr/bin/env bash

# # # # # # # # # # # # # # # # # # # # # # # # # #
# GLOBAL VARIABLES TO BE USED BY THE INSTALLER
#
# DO NOT EDIT THIS FILE
# # # # # # # # # # # # # # # # # # # # # # # # # #

# Set install directory
INSTALL_DIR="/tmp/panda64"
TOOLS_DIR="${INSTALL_DIR}/tools"
CROSS_TOOLS_DIR="${INSTALL_DIR}/cross-tools"

CROSS_COMPILE_TOOLS_DIR="${INSTALL_DIR}/cross-compile-tools"
TEMP_SYSTEM_DIR="${INSTALL_DIR}/temp-system"

HOST_TOOLS_DIR="/tools"
HOST_CROSS_TOOLS_DIR="/cross-tools"

## Rest of the configurations
HOST=$(echo ${MACHTYPE} | sed -e 's/-[^-]*/-cross/')
TARGET="x86_64-panda-linux-gnu"
TMP_PATH="/cross-tools/bin:/bin:/usr/bin"
BUILD64="-m64"
LC_ALL="POSIX"
VM_LINUZ="vmlinuz-4.4.2-systemd"
SYSTEM_MAP="System.map-4.4.2"
CONFIG_BACKUP="config-4.4.2"

# Temporary system variables
CC="${TARGET}-gcc ${BUILD64}"
CXX="${TARGET}-g++ ${BUILD64}"
AR="${TARGET}-ar"
AS="${TARGET}-as"
RANLIB="${TARGET}-ranlib"
LD="${TARGET}-ld"
STRIP="${TARGET}-strip"

# Set fonts for Help.
NORM=`tput sgr0`
BOLD=`tput bold`
REV=`tput smso`
RED=`tput setaf 1`
GREEN=`tput setaf 2`
YELLOW=`tput setaf 3`